version: '3'
services:
  selenoid:
    network_mode: bridge
    container_name: selenoid
    image: "aerokube/selenoid:latest"
    ports:
      - "4444:4444"

    volumes:
      - "/Users/olgashcherbina/Downloads/work/docker-practice-on-carina-demo/:/etc/selenoid"
      - "/Users/olgashcherbina/Downloads/work/docker-practice-on-carina-demo/video:/opt/selenoid/video"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/Users/olgashcherbina/Downloads/work/docker-practice-on-carina-demo/video
    command: [ "-conf", "/etc/selenoid/browsers.json","-video-recorder-image","selenoid/video-recorder:latest", "-video-output-dir", "/opt/selenoid/video" ]
  #    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video" ]
  selenoid-ui:
    network_mode: bridge
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui:latest"
    ports:
      - "8090:8080"
    links:
      - selenoid
    command:
      [ "--selenoid-uri", "http://selenoid:4444" ]
